<template>
  <component class="cursor-pointer" :is="icon" v-bind="$attrs" />
</template>

<script>
import {
  IconArrowRight,
  IconArrowLeft,
  IconPlus,
  IconTrendingDown,
  IconTrendingUp,
  IconX,
  IconCircleX,
  IconCircleXFilled,
  IconAdjustments,
  IconArrowLeftRight,
  IconHome2,
  IconSteeringWheel,
  IconCar,
  IconEye,
  IconEyeOff,
  IconUser,
  IconCheck,
  IconCircleCheckFilled,
  IconCircleCheck,
  IconDiscountCheckFilled,
  IconMinus,
  IconBell,
  IconTag,
  IconDots,
  IconPencil,
  IconHourglassEmpty,
  IconSettings,
  IconPower,
  IconCamera,
  IconReceiptRefund,
  IconReceipt,
  IconPhoto,
  IconBuildingBank,
  IconMapPin,
  IconSearch,
  IconChevronLeft,
  IconChevronRight,
  IconArrowNarrowUp,
  IconArrowNarrowDown,
  IconCaretDown,
  IconCalendarEvent,
  IconClock,
  IconLock,
  IconSend,
  IconArrowBadgeRightFilled,
  IconArrowBadgeRight,
  IconPointFilled,
  IconBrandGoogle,
  IconBrandFacebook,
  IconBrandStripe,
  IconBrandPaypalFilled,
  IconFile,
  IconFileImport,
  IconKeyboard,
  IconTrash,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlayerStop,
  IconQuestionMark,
  IconSquareRoundedChevronRightFilled,
  IconSquareRoundedChevronLeftFilled,
  IconHelpHexagonFilled,
  IconInfoHexagonFilled,
  IconAlertHexagonFilled,
  IconAlertTriangleFilled,
  IconArrowsExchange2,
} from "@tabler/icons-vue";

const iconMap = {
  "arrow-right": IconArrowRight,
  "arrow-left": IconArrowLeft,
  plus: IconPlus,
  "trending-down": IconTrendingDown,
  "trending-up": IconTrendingUp,
  x: IconX,
  "circle-x": IconCircleX,
  "circle-x-filled": IconCircleXFilled,
  adjustments: IconAdjustments,
  "arrow-left-right": IconArrowLeftRight,
  home2: IconHome2,
  "steering-wheel": IconSteeringWheel,
  car: IconCar,
  eye: IconEye,
  "eye-off": IconEyeOff,
  user: IconUser,
  check: IconCheck,
  "circle-check-filled": IconCircleCheckFilled,
  "circle-check": IconCircleCheck,
  "discount-check-filled": IconDiscountCheckFilled,
  minus: IconMinus,
  bell: IconBell,
  tag: IconTag,
  dots: IconDots,
  pencil: IconPencil,
  "hourglass-empty": IconHourglassEmpty,
  settings: IconSettings,
  power: IconPower,
  camera: IconCamera,
  "receipt-refund": IconReceiptRefund,
  receipt: IconReceipt,
  photo: IconPhoto,
  "building-bank": IconBuildingBank,
  "map-pin": IconMapPin,
  search: IconSearch,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "arrow-narrow-up": IconArrowNarrowUp,
  "arrow-narrow-down": IconArrowNarrowDown,
  "caret-down": IconCaretDown,
  "calendar-event": IconCalendarEvent,
  clock: IconClock,
  lock: IconLock,
  send: IconSend,
  "arrow-badge-right-filled": IconArrowBadgeRightFilled,
  "arrow-badge-right": IconArrowBadgeRight,
  "point-filled": IconPointFilled,
  "brand-google": IconBrandGoogle,
  "brand-facebook": IconBrandFacebook,
  "brand-stripe": IconBrandStripe,
  "brand-paypal": IconBrandPaypalFilled,
  file: IconFile,
  "file-import": IconFileImport,
  keyboard: IconKeyboard,
  trash: IconTrash,
  "player-pause": IconPlayerPause,
  "player-play": IconPlayerPlay,
  "player-stop": IconPlayerStop,
  "question-mark": IconQuestionMark,
  "square-rounded-chevron-right-filled": IconSquareRoundedChevronRightFilled,
  "square-rounded-chevron-left-filled": IconSquareRoundedChevronLeftFilled,
  "help-hexagon-filled": IconHelpHexagonFilled,
  "info-hexagon-filled": IconInfoHexagonFilled,
  "alert-hexagon-filled": IconAlertHexagonFilled,
  "alert-triangle-filled": IconAlertTriangleFilled,
  "arrows-exchange-2": IconArrowsExchange2,
};

export default defineComponent({
  props: {
    icon: {
      type: String,
      required: true,
      validator: (value) => value in iconMap,
    },
  },
  setup(props) {
    const icon = computed(() => {
      const selectedIcon = iconMap[props.icon];
      return selectedIcon || null;
    });

    return {
      icon,
    };
  },
});
</script>
<style scoped></style>
